# Generated by Django 6.1.1 on 2026-09-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('style', models.CharField(choices=[('portrait', 'Portrait'), ('couple', 'Couple'), ('family', 'Family'), ('friends', 'Friends'), ('anime', 'Anime'), ('milestone', 'Milestone')], default='portrait', max_length=20)),
                ('image', models.ImageField(upload_to='drawings/')),
                ('caption', models.CharField(blank=True, help_text='One line about the photo this page came from.', max_length=200)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured pages appear on the landing page.')),
                ('position', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('interest', models.CharField(choices=[('personalised', 'A personalised coloring book'), ('single_page', 'A single coloring page'), ('gift', 'A gift for someone'), ('bulk', 'Bulk or event order'), ('other', 'Something else')], default='personalised', max_length=20)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('replied', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-created'],
            },
        ),
    ]
